version: "3.8"

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/park-ia:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
